FROM python:3.11-slim

# install deps first
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy only application source code
COPY src/ ./src

# run everything from /app/src  (so imports work)
WORKDIR /app/src
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
